version: '3.1'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD:  thiago
      - MYSQL_DATABASE: redis_mysql
    ports:
      - 3306:3306
    volumes:
      - ./data/db:/var/lib/mysql