spring:
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 20000
  datasource:
    url: jdbc:mysql://localhost:3306/redis_mysql
    username: root
    password: 12345

